Env: "local"
jwt:
  secret: "mysecretkey"
  expiration: 3600 # in seconds 
grpc:
  host: "localhost"
  port: 50051
database:
  host: "auth-service-postgres"
  port: 5432  
  user: "auth_service"
  password: "changeme"  
  dbname: "auth_service_db" 