Env: "local"
database_url: "postgres://postgres:password@localhost:5432/auth_db?sslmode=disable"
jwt:
  secret: "mysecretkey"
  expiration: 3600 # in seconds 
grpc:
  host: "localhost"
  port: 50051
database:
  host: "localhost"
  port: 5432  
  user: "postgres"
  password: "password"  
  dbname: "auth_db" 